version: '2'
services:
  db:
    image: postgres:10.7
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    ports:
      - "54321:5432"      
    restart: always             
    # run as a service

  odoo12:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "12000:8069"
    tty: true
    command: -- --dev=reload
    # command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./addons:/usr/lib/python3/dist-packages/odoo/addons    
      - ./custom-addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./data:/var/lib/odoo
    restart: always             
    # run as a service
